package `in`.webxstudio.android.quoteiko

const val CHANGE_FONT_STYLE_FRAGMENT = "CHANGE_FONT_STYLE_FRAGMENT"
const val CHANGE_IMAGE_FRAGMENT = "CHANGE_IMAGE_FRAGMENT"
const val CHANGE_QUOTE_FRAGMENT = "CHANGE_QUOTE_FRAGMENT"
const val OPTIONS_FRAGMENT = "OPTIONS_FRAGMENT"

const val CURRENTLY_PREVIEWING = "CURRENTLY_PREVIEWING"

enum class ImageCardState{
    PREVIEWING,
    SELECTED,
    UNSELECTED
}